### ISSUE TITLE
git submodule foreach "(git checkout master; git pull)" not working

### ISSUE THREAD

**Issue by lewismc** [mmisw/orr#2]
Hi @carueda I'm trying to build locally for the first time in a while.
When I execute ```git submodule foreach "(git checkout master; git pull)"```... nothing is happening.
Any ideas?
Thanks

**Comment by carueda** [comment]
Hi @lewismc   Not sure, it all worked just fine a day or two ago for me when I created that latest version mentioned elsewhere. I think I even reviewed the https://github.com/mmisw/orr/blob/master/README.md 

What git version are you using?

**Comment by lewismc** [comment]
> What git version are you using?

2.20.1

I had to use ```git submodule update --init --recursive```, I'll send a PR

**Comment by carueda** [comment]
ha, you're right.  I just tried from scratch.

For starting from the `clone` operation, the key step is to use the `--recursive` flag:

```
git clone --recursive https://github.com/mmisw/orr.git
```
and this should be added to the README.  

With no `--recursive` is used for the clone, then  the step you indicate can be used.

thanks for updating the README.

**Comment by carueda** [comment]
Thanks Lewis again for your readme update PR.  I just pushed more edits to further clarify the sequence of build steps.
