### ISSUE TITLE
broken link: http://sensorml.com/ont/csm/property/SENSOR_TYPE

### ISSUE THREAD

**Issue by gwemon** [mmisw/orr#7]
Hello. Some of the concepts served by the NERC Vocab Server (NVS) are linked to concepts in MMI in ORR. It looks like the link to http://sensorml.com/ont/csm/property/SENSOR_TYPE is broken. Can you advise? Many thanks.

**Comment by carueda** [comment]
Thanks for the heads-up @gwemon . 

Could you point us to the vocabulary at NVS where this link is used? Also, do you know which ontology at the MMI ORR https://mmisw.org/ont/ contains this link?  Or maybe it is at the ORR instance at  http://sensorml.com/ont ?   Tagging  @graybeal and @mikebotts in case they can chime in.

**Comment by graybeal** [comment]
Tthis link is to a deployment of the software that was made for (and by?) Mike Botts a long time ago. I didn't even remember that this site existed in fact.

The sensorml.com site is run by him (Carlos, it's at the domain sensorml.com, which has a regular site there also), but it may be we have some access. I would expect @carueda  to know what access he has available.  

It looks like there is a problem accessing the backend, no ontologies are showing.

**Comment by graybeal** [comment]
We should look at getting the logo changed on that site—there is no way to tell that it isn't the MMI site itself. (Perhaps our Docker distributions should be shipped with a 'blank' logo.)

**Comment by carueda** [comment]
> Carlos, it's at the domain sensorml.com, which has a regular site there also

Of course I know that.  I helped set that instance up.

>  I would expect @carueda to know what access he has available.

???

I emailed Alex and Mike to see if they can adjust their instance.

**Comment by graybeal** [comment]
Thanks Carlos, that was overlapping entries. I knew you helped set it up, I just wasn't sure if you continued to have a role in maintaining it. That's all I was trying to say. Thanks for contacting Alex and Mike, it looks like they are moving to update it as we speak.

**Comment by gwemon** [comment]
> Thanks for the heads-up @gwemon .
> 
> Could you point us to the vocabulary at NVS where this link is used? Also, do you know which ontology at the MMI ORR https://mmisw.org/ont/ contains this link? Or maybe it is at the ORR instance at http://sensorml.com/ont ? Tagging @graybeal and @mikebotts in case they can chime in.

Thanks @carueda and @graybeal for the prompt response - these URIs are linked to our SWE Marine Profiles vocabularies like e.g. http://vocab.nerc.ac.uk/collection/W06/current/

**Comment by alexrobin** [comment]
@carueda @graybeal @gwemon The CSM ontology is back online so the link now resolves.
We'll also update the logo on our site. Thanks.

@gwemon We're also building new ontologies for observable properties, spectral bands, system & platform types. Feel free to link to these as well. Thanks

**Comment by gwemon** [comment]
Thanks @alexrobin. The URLs on the page http://sensorml.com/ont/csm/property/SENSOR_TYPE still do not resolve correctly though.

**Comment by alexrobin** [comment]
@gwemon Are you referring to this link: http://www.w3.org/2002/07/owl#NamedIndividual ?

If so, this is an external concept that we don't host in our ORR instance so you have to click on the icon next to it to go to the external URL.

**Comment by gwemon** [comment]
@alexrobin I tested this one which resolves okay when used in my browse: https://www.w3.org/1999/02/22-rdf-syntax-ns#type. This is why I thought in might be an issue at your end.

**Comment by graybeal** [comment]
Resolves ok (from the repo) for me now Gwen.

**Comment by alexrobin** [comment]
@graybeal @gwemon yes I did put a redirect in place for anything that's not hosted in our ORR instance, so everything in w3c namespace should now resolve directly to their site.

**Comment by gwemon** [comment]
All looking good to me too now. Thank you.

**Comment by carueda** [comment]
> The CSM ontology is back online so the link now resolves.
We'll also update the logo on our site.
> ..
> We're also building new ontologies ...

@alexrobin that all sounds great, thanks!  (btw, you may want to install the latest orr version ; )

@gwemon  Thanks again for the heads-up. I'm closing this now.
